# Generated by Django 3.1.7 on 2021-03-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210304_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_instock',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
