# Generated by Django 3.1.7 on 2021-03-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210304_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_instock',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
